### PR TITLE
Add whistle's list of providers

### PR DESCRIPTION
**Pull request by kjonick1**
Created a new container that will contain the providers.  Whistle and Unif.io uses a different set of providers, so doesn't make sense to include in the terraform container.  The CI container will pull this in and copy providers into CI container path.

### CODE REVIEW

**Comment by kjonick1** [comment]
Can I also get your help to setup the Circle CI build?

**Review by pickgr — COMMENTED** [review]
Can we add the GitHub provider too?  We're not actually using it yet but have a story to do so soon.

**Comment by pickgr** [comment]
Yeah - how can I help with CircleCI?  I should be pretty free tomorrow - just one meeting scheduled at 1pm PT

**Review by pickgr — APPROVED** [review]

**Comment by kjonick1** [comment]
I have the Circle build setup, I just need to repository setup in Docker Hub.  Can you create 'terraform-providers' under whistle for me?  I'm going to merge this, but the master build will fail until that is created.

**Comment by pickgr** [comment]
Hi Kathy,

It should be ready at https://hub.docker.com/r/whistle/terraform-providers/  It's a public repo.

**Pull request merged**
